### ISSUE TITLE
Switch from zip to installer

### ISSUE THREAD

**Issue by joshuacant** [streamlink/streamlink-twitch-gui-chocolatey#32]
Hi, would it be possible to switch this package from using the zip file (extracted to choco's lib folder) to the actual installer? I notice the streamlink package is using the installer method, but this one is not.

Thanks for considering this change, and I appreciate all the work you've done.

**Comment by scowalt** [comment]
In situations like this, software will tend to have 3 chocolatey packages: an "install" package while uses the installer, a "portable" package which uses the zip file, and a "main" package which installs the "install" package. [See 7zip as an example
](https://chocolatey.org/search?q=7zip)
![image](https://user-images.githubusercontent.com/1100550/72755596-b910e900-3b7f-11ea-92ec-d81766fb17ba.png)

Ideally, we would follow this same structure, since streamlink-twitch-gui has portable and install versions.

(I won't be able to look at this anytime soon, just wanted to give some background)

Thanks for the feedback!

**Comment by bastimeyer** [comment]
As an addition from my side, I personally haven't tested a silent install yet, but after checking the [`installer.nsi`](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.9.0/build/resources/installer/installer.nsi) and NSIS documentation again, I think it \*should\* be fine.

Parameters are documented here:
https://nsis.sourceforge.io/Docs/Chapter3.html#installerusage
