### ISSUE TITLE
Update to 2.3.0

### ISSUE THREAD

**Issue by SAJewers** [streamlink/streamlink-twitch-gui-chocolatey#55]
https://github.com/streamlink/streamlink-twitch-gui/releases/tag/v2.3.0

**Comment by scowalt** [comment]
Thanks for the ping! This should be automated but the automation gets disabled after 60 days of inactivity. 

This just got submitted https://community.chocolatey.org/packages/streamlink-twitch-gui/2.3.0

**Comment by bastimeyer** [comment]
Thanks for the package update, @scowalt 

Please have a look at the GitHub actions warnings:
https://github.com/streamlink/streamlink-twitch-gui-chocolatey/actions/runs/5814724283

1. node12 is EOL and gets replaced by node16
2. `set-output` is deprecated
3. invalid input for the `EndBug/add-and-commit@v8` action (using a branch/tag name instead of an explicit commit ID for external actions allows bad actors to potentially hijack the repo and read secret env vars)

**Comment by scowalt** [comment]
Fixed with https://github.com/streamlink/streamlink-twitch-gui-chocolatey/commit/ab5db996e9c05523c20dc58da919747a882df8b9

https://github.com/streamlink/streamlink-twitch-gui-chocolatey/actions/runs/5849708855

There's one warning left and it appears to be this issue https://github.com/EndBug/add-and-commit/issues/516
