### ISSUE TITLE
The installers of 1.0.0 and 1.0.1 have been deleted

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink-twitch-gui-chocolatey#6]
I had to delete the installers of the 1.0.0 and 1.0.1 releases because of a critical bug / logic error.
https://github.com/streamlink/streamlink-twitch-gui/commit/f6d03f0077e3774217f212061f1c9a66aa1a4f2f
You can probably guess what happened to one of the users who chose a wrong install path. 😞 

I just wanted to let you know, in case this gets reported, because this breaks the choco package.

Btw, the required min. streamlink version will be `0.2.0` in the next release. I have just seen that you've updated the package.
Can the choco package stuff be removed from the main repo?

This thread can be closed once the next release gets published, which I'm intending to do later today.

**Comment by scowalt** [comment]
I don't think this affects the chocolatey package since I'm still using the ZIP file releases in the Chocolatey package (not the installer). If the ZIP files didn't get deleted or replaced then the Chocolatey world should be unchanged. Sorry to hear about that bug!

Feel free to remove the Chocolatey stuff from the streamlink-twitch-gui repo (or assign a bug to me to do it and I'll get around to it). It doesn't make sense to have it in two places and this seems like a nice home for it. If I still want to automate the release I can pull those scripts into this repo, though there is probably a better way to automate packages by now that I haven't explored.

I'll make sure to bump the streamlink dependency version for the next release (see this PR for the status of the 0.2.0 streamlink chocolatey release: https://github.com/streamlink/streamlink-chocolatey/pull/5)

**Comment by bastimeyer** [comment]
> I'm still using the ZIP file releases

You're right... I had the streamlink installer in mind, oops...

> Feel free to remove the Chocolatey stuff

I have already removed all the stuff 😄 

> I'll make sure to bump the streamlink dependency

Thanks. Happy new year btw 🎉
